#!/bin/bash
# Builds Assets/RealisticClassroom/Documentation/Documentation.pdf (+ README.md) from Publishing/doc-src/Documentation.src.md and the validator statistics.
set -e
cd "$(dirname "$0")/.."
OUT="../ARClassroom/Assets/RealisticClassroom/Documentation"
mkdir -p "$OUT" build
python3 - <<'PY'
import re
src=open('doc-src/Documentation.src.md').read()
try:
    rep=open('reports/validation.md').read()
    stats=rep[rep.index('## Prefab statistics'):]
    stats=stats.replace('## Prefab statistics','Triangle counts, materials and real-world sizes of every prefab (generated from the shipped assets):',1)
except Exception:
    stats='(statistics are generated by the pre-flight validator)'
import os
src=src.replace('<!--STATS-->',stats)
env={}
if os.path.exists('publisher.env'):
    for line in open('publisher.env'):
        line=line.strip()
        if line and not line.startswith('#') and '=' in line:
            k,v=line.split('=',1); env[k.strip()]=v.strip().strip('"').strip("'")
for ph,key in (('[PUBLISHER NAME]','PUBLISHER_NAME'),('[SUPPORT EMAIL]','SUPPORT_EMAIL'),('[WEBSITE]','WEBSITE')):
    if env.get(key): src=src.replace(ph,env[key])
    else: print('WARNING: '+key+' not set in Publishing/publisher.env - placeholder '+ph+' stays in the documentation')
open('build/Documentation.md','w').write(src)
PY
python3 tools/md2html.py build/Documentation.md build/Documentation.html "Classroom Interior Pack - Documentation"
"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --headless=new --disable-gpu --no-pdf-header-footer --print-to-pdf="$OUT/Documentation.pdf" "file://$(pwd)/build/Documentation.html" 2>/dev/null
cat > "$OUT/../README.md" <<'MD'
# Classroom Interior Pack - Animated Teacher & Students (URP)

Open `Scenes/Classroom_Demo.unity` and press Play. Requires Unity 6 with the Universal Render Pipeline.
Full documentation: `Documentation/Documentation.pdf`. Optional one-click URP setup: **Tools > Realistic Classroom > Apply Recommended URP Settings**.
MD
ls -la "$OUT"
